Update labs to use NUCLEO-F303
CalSol/braintrain pull request #8
Opened 2021-09-15 05:52 UTC by dragonlock2

2021-09-15 08:56 UTC, ducky64 requested changes
Mostly looks good, some inline comments. Thanks for all the copy-editing!

Other issues:
- Where'd the breadboard file come from? Do we have the rights to use it and license it under the repository-wide license? We also might have a breadboard diagram from other training materials.
- Do we want to (and can we) write the text so it doesn't refer to any dev board, so if we end up doing this again, we'll have less changes?
- Do we still notice lag with floating point? The F303K8 has a FPU, doesn't it? If the floating point overhead is insignificant, I'm not sure how we want to write this section - perhaps disable the FPU in the compiler flags, slow down the processor clock, or get rid of it entirely (not preferred - this is an embedded gotcha)?

2021-09-15 08:56 UTC, ducky64 commented on lab1.md
> +![Image](docs/breadboard.jpg?raw=true)
Might be useful to show the circuit diagram, and the breadboard diagram.

From the [ancient training documents](https://github.com/CalSol/training-docs), we had pictures that looked like this:
![image](https://user-images.githubusercontent.com/1069863/133400089-997bff3a-2eba-46bd-a8e3-a209633ac7f7.png)
I can make updated diagrams - and I think diagrams might be more intuitive than a long text list? Feel free to leave a TODO here in this case.

2021-09-15 08:56 UTC, ducky64 commented on lab1.md
>  This should fade the RGB LED through all the colors over a period of 3 seconds.
TODO we should also add something with the button

2021-09-15 08:56 UTC, ducky64 commented on lab1.md
>  ## Lab 1.1: Getting started
Consider moving this to the pre-lab (especially if the campus wifi is still terribad), and consider moving the pairing up blurb to the actual lab part?

2021-09-15 08:56 UTC, ducky64 commented on lab1.md
> +PwmOut ledR(D9);
Is D9 to avoid using the CAN pin D10?

2021-09-15 08:56 UTC, ducky64 commented on lab1.md
> +Before we get to coding, we need to setup the NUCLEO-F303K8 on a breadboard and connect an RGB LED and button to it. The pinout for the board can be found [here](https://os.mbed.com/platforms/ST-Nucl
Perhaps inline embed the [F303K8 pinout image](https://os.mbed.com/media/uploads/bcostm/nucleo_f303k8_2017_10_10.png) (link only - do not commit the image to this repo unless we're sure about the rights)?

2021-09-21 04:53 UTC, dragonlock2 commented on lab1.md
> +![Image](docs/breadboard.jpg?raw=true)
diagrams are added

2021-09-21 04:54 UTC, dragonlock2 commented on lab1.md
> +PwmOut ledR(D9);
yup

2021-09-21 04:55 UTC, dragonlock2 commented on lab1.md
> +Before we get to coding, we need to setup the NUCLEO-F303K8 on a breadboard and connect an RGB LED and button to it. The pinout for the board can be found [here](https://os.mbed.com/platforms/ST-Nucl
embedded

2021-09-21 04:57 UTC, dragonlock2 commented
- breadboard picture removed
- definitely something to do in the future
- switching to f042k6 so no longer relevant (did do a test on the f303k7 earlier and appeared that fpu was being used)

2021-09-21 05:16 UTC, dragonlock2 commented on lab1.md
>  This should fade the RGB LED through all the colors over a period of 3 seconds.
added a sanity check code to more easily tell if its working

2021-09-21 09:14 UTC, ducky64 approved these changes

2021-09-21 09:14 UTC, merged